version: '3.8' 

services:
  
  ubuntu1:
    hostname: ubuntu1
    container_name: ubuntu1
    build:
      context: .
      dockerfile: Dockerfile.local
    ports: 
     - 22:22
    privileged: true
    networks:
     - ansible.dev

  ubuntu2:
    hostname: ubuntu2
    container_name: ubuntu2
    build:
      context: .
      dockerfile: Dockerfile.local
    ports: 
     - 22:22
    privileged: true
    networks:
     - ansible.dev



networks:
  ansible.dev:
    name: ansible.dev